global:
 name: consul
 datacenter: dc1
 gossipEncryption:
  autoGenerate: true
 tls:
  enabled: true
  httpsOnly: false
  enableAutoEncrypt: true
  verify: true
# peering:
 acls:
  manageSystemACLs: true
  createReplicationToken: true
connectInject:
  enabled: true
server:
 replicas: 1
 # exposeService:
 # enabled: true
 exposeGossipAndRPCPorts: true
ui:
 enabled: true
 service:
  enabled: true
  type: LoadBalancer
dns:
 enabled: true
### Gateways can be deployed later ###
ingressGateways:
 enabled: true
 replicas: 1
 gateways:
 - name: ingress-gateway
   service:
    type: LoadBalancer
    ports: 
    - port: 8080
# meshGateway: