apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: dashboard
          hosts: ["*"]
    - port: 8443
      protocol: http
      services:
        - name: dashboard
          hosts: ["*"]          