apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "internal"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
spec:
  selector:
    app: backend
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nicholasjackson/fake-service:v0.25.2
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            - name: 'UPSTREAM_URIS'
              value: "http://redis.service.consul:9090,http://database.service.database.consul:9090,http://internal-a6dddb34bc42842ffaa44ec779f69241-154475179.us-east-2.elb.amazonaws.com:9090"
            - name: 'NAME'
              value: 'backend'
            - name: 'MESSAGE'
              value: 'I have an ingress'