apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-ro
---
apiVersion: v1
kind: Service
metadata:
  name: database-ro
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "internal"
    consul.hashicorp.com/service-name: "database"
    consul.hashicorp.com/service-tags: "read-only"
spec:
  type: LoadBalancer
  selector:
    app: database-ro
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-ro
  labels:
    app: database-ro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database-ro
  template:
    metadata:
      labels:
        app: database-ro
    spec:
      containers:
        - name: database-ro
          image: nicholasjackson/fake-service:v0.25.2
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            - name: 'NAME'
              value: 'Read Only database - running in EKS'
            - name: 'MESSAGE'
              value: 'I do not have an ingress'