apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-rw
---
apiVersion: v1
kind: Service
metadata:
  name: database-rw
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "internal"
    consul.hashicorp.com/service-name: "database"
    consul.hashicorp.com/service-tags: "read-write"
spec:
  type: LoadBalancer
  selector:
    app: database-rw
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-rw
  labels:
    app: database-rw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-rw
  template:
    metadata:
      labels:
        app: database-rw
    spec:
      containers:
        - name: database-rw
          image: nicholasjackson/fake-service:v0.25.2
          ports:
            - containerPort: 9090
          env:
            - name: 'LISTEN_ADDR'
              value: '0.0.0.0:9090'
            - name: 'NAME'
              value: 'Read/Write database - running in EKS'
            - name: 'MESSAGE'
              value: 'I do not have an ingress'