apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      # annotations:
      #   'consul.hashicorp.com/connect-inject': 'true'
      #   'consul.hashicorp.com/transparent-proxy': 'false'        
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nicholasjackson/fake-service:v0.24.2
        env:
        - name: NAME
          value: API (Not in the mesh)        
        - name: UPSTREAM_URIS
          value: http://cache.default.svc.cluster.local:9091
        ports:
        - containerPort: 9090
      serviceAccountName: api
