apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nicholasjackson/fake-service:v0.24.2
        env: 
        - name: UPSTREAM_URIS
          value: http://api.default.svc.cluster.local:9090,http://cache.default.svc.cluster.local:9091
          #value: http://cache.default.svc.cluster.local:9091
        - name: NAME
          value: Frontend (Only in the mesh)
        ports:
        - containerPort: 9090
      serviceAccountName: frontend
